image_width: 320
image_height: 240
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [200, 0, 160, 0, 200, 120, 0, 0, 1]
distortion_model: "plumb_bob"
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.1, 0.1, 0.01, 0.01]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [200, 0, 160, 0, 0, 200, 120, 0, 0, 0, 1, 0]
